runtime: python38
# service: default
#runtime: python38

# basic_scaling:
#    max_instances: 2
#    idle_timeout: 10m

resources:
   cpu: 1
   memory_gb: 4
   disk_size_gb: 10

# entrypoint: gunicorn -b 0.0.0.0:8080 main:app.server --timeout 60 --workers 1
entrypoint: gunicorn -b 0.0.0.0:8080 main:server
